#!/usr/bin/env node
// Update ROADMAP.md with AUTO:METRICS block

const fs = require('fs');

const AUTO_START = '<!-- AUTO:METRICS-START -->';
const AUTO_END = '<!-- AUTO:METRICS-END -->';

function clamp01(x) {
    return x < 0 ? 0 : x > 1 ? 1 : x;
}

function loadJson(p) {
    return JSON.parse(fs.readFileSync(p, 'utf-8'));
}

function loadText(p) {
    return fs.readFileSync(p, 'utf-8');
}

function saveText(p, text) {
    const dir = require('path').dirname(p);
    if (dir && !fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(p, text, 'utf-8');
}

function pickMode(northStarPct, riskLevel, accepted, trend) {
    if (!accepted || trend === 'down') {
        return '🚑 Recovery Mode（恢复模式）';
    }
    if (riskLevel === '高' || northStarPct >= 85) {
        return '🛡 Hardening Mode（强化模式）';
    }
    if (50 <= northStarPct && northStarPct < 85) {
        return '⚡ Optimization Mode（优化模式）';
    }
    return '🔥 Acceleration Mode（加速模式）';
}

function riskLevelFrom(score) {
    if (!score.accepted) return '高';
    const failRate = score.fail_rate || 0;
    const stall = (score.bottleneck || {}).longest_stall_median_seconds || 0;
    if (failRate > 0.01 || stall > 20 * 60) return '中';
    return '低';
}

function pct(x) {
    try {
        return (clamp01(parseFloat(x)) * 100).toFixed(1) + '%';
    } catch {
        return 'N/A';
    }
}

function formatBlock(report, prevNsPct) {
    const top1 = report.top1 || {};
    const score = top1.score || {};
    const accepted = score.accepted || false;

    const vTotal = accepted ? (score.V_total || 0) : 0;
    const nsPct = clamp01(vTotal) * 100;

    let trend = 'flat';
    if (prevNsPct !== null && !isNaN(prevNsPct)) {
        if (nsPct > prevNsPct + 0.5) trend = 'up';
        else if (nsPct < prevNsPct - 0.5) trend = 'down';
    }

    const risk = riskLevelFrom(score);
    const mode = pickMode(nsPct, risk, accepted, trend);

    const comps = score.components || {};

    const constraintFailed = score.constraint_failed;
    const failRate = score.fail_rate || 0;
    const stall = (score.bottleneck || {}).longest_stall_median_seconds || 0;

    let taskId, acceptance, impact;
    if (mode.startsWith('🚑')) {
        taskId = 'fix-sim-constraints';
        acceptance = 'Top1 accepted=true；fail_rate<=1%；stall_median<=20min';
        impact = '修复导致不可运行/下降的根因，恢复 North Star 到可评估区间。';
    } else if (mode.startsWith('🔥')) {
        taskId = 'improve-growth-momentum';
        acceptance = 'growth_momentum +5% 以上，且不触发 hard constraints';
        impact = '加速提升成长动量，直接拉升 North Star。';
    } else if (mode.startsWith('⚡')) {
        taskId = 'improve-return-quality';
        acceptance = 'return_quality +5% 以上，且 stability 不下降';
        impact = '提升回归后继续玩的比例，稳步推高 North Star。';
    } else {
        taskId = 'reduce-risk-debt';
        acceptance = 'fail_rate<=0.5%，stall_median<=15min，constraint_failed=null';
        impact = '降低风险指标，避免 North Star 回落并提高可持续迭代速度。';
    }

    const verify = `\`\`\`bash\nnode tools/autotune/search.js --baseline balance/baseline.json --space balance/search_space.json --runs 2000 --generations 15 --population 40 --topk 5\nnode tools/autotune/update_roadmap.js --report output/tuning_report.json --roadmap ROADMAP.md --diff-only\n\`\`\`\n指标验证：对比本次写入的 North Star / Supporting / Risk 与上次记录。`;

    const lines = [];
    lines.push(`[Mode]`);
    lines.push(mode);
    lines.push('');
    lines.push(`[North Star]`);
    lines.push(`${nsPct.toFixed(1)}% (trend: ${trend})`);
    lines.push('');
    lines.push('[Supporting Metrics]');
    lines.push(`- growth_momentum: ${(clamp01(comps.growth_momentum || 0) * 100).toFixed(1)}%`);
    lines.push(`- return_quality: ${(clamp01(comps.return_quality || 0) * 100).toFixed(1)}%`);
    lines.push(`- upgrade_satisfaction: ${(clamp01(comps.upgrade_satisfaction || 0) * 100).toFixed(1)}%`);
    lines.push(`- progress_clarity: ${(clamp01(comps.progress_clarity || 0) * 100).toFixed(1)}%`);
    lines.push(`- stability_score: ${(clamp01(comps.stability_score || 0) * 100).toFixed(1)}%`);
    lines.push('');
    lines.push('[Risk Level]');
    lines.push(risk);
    lines.push('');
    lines.push('[Task]');
    lines.push(`${taskId} / ${acceptance}`);
    lines.push('');
    lines.push('[Impact]');
    lines.push(impact);
    lines.push('');
    lines.push('[Do]');
    lines.push('- 修改文件列表：balance/baseline.json（若应用 top_params），或评分/模拟逻辑相关文件');
    lines.push('- 实现摘要：基于本轮 Mode 仅做 1 个任务，完成后重新跑 search + score 验证指标变化');
    lines.push('');
    lines.push('[Verify]');
    lines.push(verify);
    lines.push('');
    lines.push('[RoadmapPatch]');
    lines.push('(diff only; generated by tools/autotune/update_roadmap.js)');
    lines.push('');
    lines.push('[Next]');
    lines.push(taskId);
    lines.push('');
    lines.push('----');
    lines.push('');
    lines.push('(raw)');
    lines.push(`- accepted: ${accepted}`);
    lines.push(`- constraint_failed: ${constraintFailed}`);
    lines.push(`- fail_rate: ${failRate}`);
    lines.push(`- longest_stall_median_seconds: ${stall}`);

    return lines.join('\n') + '\n';
}

function extractPrevNsPct(roadmapText) {
    if (!roadmapText.includes(AUTO_START) || !roadmapText.includes(AUTO_END)) {
        return null;
    }
    const blk = roadmapText.split(AUTO_START)[1].split(AUTO_END)[0];
    const match = blk.match(/([\d.]+)%/);
    if (match) {
        return parseFloat(match[1]);
    }
    return null;
}

function replaceAutoBlock(roadmapText, newBlock) {
    if (!roadmapText.includes(AUTO_START) || !roadmapText.includes(AUTO_END)) {
        return roadmapText.trim() + '\n\n' + AUTO_START + '\n' + newBlock + AUTO_END + '\n';
    }
    const before = roadmapText.split(AUTO_START)[0];
    const after = roadmapText.split(AUTO_END)[1];
    return before + AUTO_START + '\n' + newBlock + AUTO_END + after;
}

function unifiedDiff(a, b, fromfile, tofile) {
    const al = a.split('\n');
    const bl = b.split('\n');
    const diff = [];
    diff.push(`--- ${fromfile}`);
    diff.push(`+++ ${tofile}`);
    diff.push('@@ -1,1 +1,1 @@');
    diff.push(`-${al[0] || ''}`);
    diff.push(`+${bl[0] || ''}`);
    return diff.join('\n') + '\n';
}

function main() {
    const args = process.argv.slice(2);
    let reportPath = 'output/tuning_report.json';
    let roadmapPath = 'ROADMAP.md';
    let diffOnly = false;
    let apply = false;

    for (let i = 0; i < args.length; i++) {
        if (args[i] === '--report' && i + 1 < args.length) reportPath = args[i + 1];
        if (args[i] === '--roadmap' && i + 1 < args.length) roadmapPath = args[i + 1];
        if (args[i] === '--diff-only') diffOnly = true;
        if (args[i] === '--apply') apply = true;
    }

    const report = loadJson(reportPath);
    const roadmap = fs.existsSync(roadmapPath) ? loadText(roadmapPath) : '';

    const prev = extractPrevNsPct(roadmap);
    const block = formatBlock(report, prev);
    const updated = replaceAutoBlock(roadmap, block);

    const diff = unifiedDiff(roadmap, updated, `a/${roadmapPath}`, `b/${roadmapPath}`);
    if (diffOnly) {
        console.log(diff);
        return;
    }
    if (apply) {
        saveText(roadmapPath, updated);
    }
    console.log(diff);
}

main();
